services:
  pg:
    image: postgres:16
    environment:
      POSTGRES_DB: bench
      POSTGRES_USER: bench
      POSTGRES_PASSWORD: bench
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    command: ["postgres", "-c", "shared_buffers=256MB", "-c", "max_connections=200"]
volumes:
  pgdata:
