# application.yml（抜粋）
spring:
  application:
    name: pg-bench

# --- JDBC プロファイル ---
---
spring:
  config:
    activate:
      on-profile: jdbc
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/bench
    username: bench
    password: bench
    hikari:
      maximum-pool-size: 20
  main:
    web-application-type: servlet

# --- R2DBC プロファイル ---
---
spring:
  config:
    activate:
      on-profile: r2dbc
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bench
    username: bench
    password: bench
    pool:
      max-size: 20
  main:
    web-application-type: servlet
