spring:
  application:
    name: pg-bench

  flyway:
    enabled: true
    locations: classpath:db/migration

# --- JDBC プロファイル ---
---
spring:
  config:
    activate:
      on-profile: jdbc
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcTransactionManagerAutoConfiguration
  datasource:
    url: jdbc:postgresql://localhost:5432/bench
    username: bench
    password: bench
    hikari:
      maximum-pool-size: 20
    driver-class-name: org.postgresql.Driver
  main:
    web-application-type: servlet

bench:
  seed:
    enabled: true
    rows: 200_000

# --- R2DBC プロファイル ---
---
spring:
  config:
    activate:
      on-profile: r2dbc
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.jdbc.JdbcTemplateAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
      - org.springframework.boot.autoconfigure.flyway.FlywayAutoConfiguration
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/bench
    username: bench
    password: bench
    pool:
      max-size: 20
  flyway:
    enabled: false
  datasource:
    # Flyway用にJDBCも必要（R2DBCのみだとFlywayが動かない）
    url: jdbc:postgresql://localhost:5432/bench
    username: bench
    password: bench
    hikari:
      maximum-pool-size: 5
  main:
    web-application-type: servlet

bench:
  seed:
    enabled: false
    rows: 200_000
